### ISSUE TITLE
Getting missing argument error when trying to install

### ISSUE THREAD

**Issue by agolajko** [ankitchiplunkar/cairo-jupyter#11]
Hi there,

When trying to installing this package I get the following error:
`   TypeError: __init__() missing 1 required positional argument: 'builtins' `

I have started a new virtual env and also downloaded  ipykernel it first asked me to.

Do you have any pointers why I might be getting this issue?

**Comment by ankitchiplunkar** [comment]
sorry that was a regression, have fixed it in the latest version
here is a PR which fixes the issue: https://github.com/ankitchiplunkar/cairo-jupyter/pull/12

**Comment by agolajko** [comment]
thanks for the quick fix!
