### ISSUE TITLE
No Cairo option when notebook start

### ISSUE THREAD

**Issue by agolajko** [ankitchiplunkar/cairo-jupyter#13]
Hey, thanks for the quick fix to the previous issue. 

The package installs now which is great, and I am able to run the `jupyter notebook` command from within the environment where `cairo-kernel` is installed.
The Cairo option doesn't yet show up in after the notebook starts (as is visible in the how to GIF in the README). 

Thanks for your help
![image](https://user-images.githubusercontent.com/57454127/149329214-77f2ea53-7d43-4376-8482-1f6d543b6018.png)

**Comment by ankitchiplunkar** [comment]
hmm, can you paste the did you install it in a virtualenviornment?

were you able to see this message while installation?

```
Installing Jupyter kernel spec
```

**Comment by ankitchiplunkar** [comment]
found and fixed the issue
